import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    paddingTop: 90,
    justifyContent: 'center',
    marginHorizontal: 20,
  },
  textDesc1: {
    fontSize: 17,
    color: ' #A0A3BD',
  },
  textDesc2: {
    fontSize: 40,
    fontWeight: 'bold',
    color: '#5F2EEA',
  },
  imageBox: {
    marginTop: 30,
    width: 370,
    height: 450,
    resizeMode: 'stretch',
    marginBottom: 100,
  },
  backgroundColor: {
    backgroundColor: '#D6D8E7',
    height: 510,
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  nowShowingHeader: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    padding: 10,
  },
  nowShowing: {
    fontSize: 20,
    color: '#5F2EEA',
    fontWeight: 'bold',
  },
  viewAll: {
    color: 'black',
  },
  card: {
    backgroundColor: 'whitesmoke',
    padding: 20,
    borderRadius: 12,
    textAlign: 'center',
    marginRight: 20,
    width: 195,
  },
  imageCard: {
    width: '100%',
    height: 200,
    resizeMode: 'stretch',
    marginBottom: 10,
  },
  movieText: {
    textAlign: 'center',
    color: 'black',
    fontSize: 12,
  },
  movieText2: {
    textAlign: 'center',
    marginTop: 12,
    fontSize: 12,
  },
  buttonViewAll: {
    marginTop: 20,
    textAlign: 'center',
    backgroundColor: 'gainsboro',
    paddingVertical: 10,
    borderRadius: 12,
    borderColor: '#5F2EEA',
  },
  buttonViewAllText: {
    textAlign: 'center',
    color: '#5F2EEA',
    fontSize: 12,
  },
  containers: {
    paddingTop: 40,
    justifyContent: 'center',
    marginHorizontal: 20,
  },
  scroll: {
    flexDirection: 'row',
    padding: 10,
    overflow: 'visible',
    marginTop: 20,
    marginBottom: 10,
  },
  button: {
    marginRight: 15,
    backgroundColor: 'gainsboro',
    paddingHorizontal: 30,
    paddingVertical: 10,
    borderRadius: 12,
    borderColor: '#5F2EEA',
  },
  buttonText: {
    fontWeight: 'bold',
    color: '#5F2EEA',
  },
  cardUpcoming: {
    backgroundColor: '#D6D8E7',
    padding: 20,
    borderRadius: 12,
    textAlign: 'center',
    marginRight: 20,
    width: 195,
  },
  buttonUpcoming: {
    marginTop: 20,
    textAlign: 'center',
    backgroundColor: 'whitesmoke',
    paddingVertical: 10,
    borderRadius: 12,
    borderColor: '#5F2EEA',
  },
  inputBox1: {
    marginTop: 40,
    textAlign: 'center',
    fontSize: 15,
  },
  inputBox2: {
    textAlign: 'center',
    fontSize: 35,
    color: '#5F2EEA',
    marginBottom: 30,
  },
  textInputBox: {
    backgroundColor: 'gainsboro',
    borderRadius: 10,
    paddingHorizontal: 20,
    marginHorizontal: 20,
  },
  buttonJoinNow: {
    backgroundColor: '#5F2EEA',
    marginHorizontal: 20,
    marginTop: 20,
    paddingVertical: 15,
    borderRadius: 7,
  },
  buttonJoinText: {
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 15,
  },
  textJoinNow: {
    textAlign: 'center',
    marginHorizontal: 20,
    marginTop: 30,
    fontSize: 14,
    marginBottom: 30,
  },
});
